FROM debian:12-slim
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server curl ca-certificates sudo && rm -rf /var/lib/apt/lists/* && mkdir -p /run/sshd && useradd -m -s /bin/bash user && mkdir -p /home/user/.ssh
COPY portainer_lite_key.pub /home/user/.ssh/authorized_keys
RUN chmod 700 /home/user/.ssh && chmod 600 /home/user/.ssh/authorized_keys && chown -R user:user /home/user/.ssh && echo 'user ALL=(ALL) NOPASSWD:ALL' >/etc/sudoers.d/user && chmod 440 /etc/sudoers.d/user
CMD ["/usr/sbin/sshd","-D","-e"]
